app/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views


# Blog connexions by CarlaPastor
urlpatterns = [
    url(r"^", include("worldcup.urls", namespace="worldcup")),
    url(r"^", include("polls.urls", namespace="polls")),
    url(r"^admin/", admin.site.urls),
    url(r"^accounts/", include("accounts.urls", namespace="accounts")),
    url(r"^thanks/$", views.ThanksPage.as_view(), name="thanks"),
]

blogPy/blogPy/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views


# Blog connexions by CarlaPastor
urlpatterns = [
    url(r"^$", views.HomePage.as_view(), name="home"),
    url(r"^admin/", admin.site.urls),
    url(r"^accounts/", include("accounts.urls", namespace="accounts")),
    url(r"^accounts/", include("django.contrib.auth.urls")),
    url(r"^test/$", views.TestPage.as_view(), name="test"),
    url(r"^thanks/$", views.ThanksPage.as_view(), name="thanks"),
]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'

urlpatterns = [
    path('indexpolls', views.indexpolls, name='indexpolls'),
    path('<int:question_id>/detail/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('<int:question_id>/vote/results/', views.vote, name='vote'),


    ]

worldcup/urls.py
from django.urls import path
from . import views

app_name = 'worldcup'

urlpatterns = [
    path('', views.index, name='index'),
    path('scores/', views.scores, name='scores'),
    path('twitter/', views.twitterfeed, name='twitter'),
    path('teams/', views.search_team, name="teams"),
    path('history/', views.history, name="history"),
    path('contact/', views.contact, name="contact"),
]

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% url 'worldcup:scores' as scores %}
{% url 'worldcup:twitter' as twitter %}
{% url 'worldcup:index' as homepage %}
{% url 'worldcup:teams' as teams %}
{% url 'worldcup:blog' as blog %}
{% url 'worldcup:history' as history %}
{% url 'worldcup:contact' as contact %}
{% url 'polls:indexpolls' as indexpolls %}

<html lang="en">

    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">

    {% block head %}
        <title>World Cup For Americans</title>
    {% endblock %}

    </head>

    <nav class="navbar navbar-expand-md navbar-light bg-light">
        <a class="nav navbar-brand" href="{{homepage}}">
            <img src="{% static 'images/worldcup.png' %}" class="rounded" alt="..." style="max-height: 75px">
        </a>
        <a class="nav navbar-brand" href="{{homepage}}">
          <h1><b>World Cup For Americans</b></h1>
          <b><sub><center>Russia 2018</center></sub></b>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse navbar-brand" id="navbarNav">
            <ul class="nav navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{{history}}">|<b>  History </b></a>
                  </li>

                <li class="nav-item">
                    <a class="nav-link" href="{{teams}}">|<b>  Teams </b></a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{{scores}}">|<b> Scores </b><span class="sr-only">(current)</span></a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{{twitter}}">|<b> Twitter Feed </b></a>
                </li>

                <li class="nav-item">
                  <a class="nav-link" href="http://www.ussoccer.live/">|<b>  Join our Social Blog</b></a>
                </li>

                <li class="nav-item">
                  <a class="nav-link" href="{{indexpolls}}">|<b> Polls</b></a>
                <li class="nav-item">
                    <a class="nav-link" href="{{contact}}">|<b> Contact </b></a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="https://www.fifa.com/worldcup/">|<b> FIFA/worldcup </b></a>
                </li>
            </ul>

        </div>
    </nav>

    {% block content %}

    {% endblock %}

    <footer class="card-footer">
        <p class="m-1"> © 2018 Team9, CIS4930 🐍 </p>

    </footer>

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>


    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">


</html>

templates/index.html
{% extends "base.html" %}

{% block content %}

    <div class="jumbotron">
            <div class="m-auto" style="width: 560px;clear:left ">
                 <iframe width="660" height="415" src= "https://www.youtube.com/embed/BL5iaUSlpqA" style="border:2px solid red;" frameborder="5" allow="autoplay; encrypted-media" allowfullscreen=""></iframe>
            </div>
            
    
    <div class="container text-justify">
        <p class="">

           

            The 2018 FIFA World Cup is the 21st FIFA World Cup, a quadrennial international football tournament
            contested by the men's national teams of the member associations of FIFA.
        </p>

        <p>
            It is currently ongoing in Russia starting from 14 June and will end with the final match on 15 July 2018.
            This is the first World Cup to be held in Eastern Europe,and the eleventh time that it has been held in Europe. For the first time the tournament takes place on two continents – Europe and Asia.
            All but one of the stadium venues are in European Russia in order to keep travel time manageable. At an estimated cost of over $14.2 billion, it is the most expensive World Cup ever.
            This is also the first World Cup where video assistant referees (VARs) have been utilised. </p>
        <p>
            The final tournament involves 32 national teams, which include 31 teams determined through qualifying competitions and the automatically qualified host team.
            Of the 32 teams, 20 made back-to-back appearances following the last tournament in 2014, including defending champions Germany, while both Iceland and Panama made their first appearances at a FIFA World Cup.
            A total of 64 matches will be played in 12 venues located in 11 cities. The final will take place on 15 July at the Luzhniki Stadium in Moscow
        </p>
    </div>
    <div class="container text-center">
            <p class="">
               _______________________________________________________________________________________________________________________________________________________________________
            </p>
        </div>

    <div class="container">

        <h2> Today's Matches </h2>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope ="col"> Time </th>
                    <th scope="col">Match</th>
                </tr>
            </thead>
            {% for item in match_query %}
                <tbody>
                <tr>
                    <td> {{ item.startTime }}</td>
                    <td> {{ item.LeftTeam }} vs. {{item.RightTeam}} </td>
                </tr>
                </tbody>
            {% endfor %}
        </table>

    </div>
    <div class="container text-center">
            <p class="">
               _______________________________________________________________________________________________________________________________________________________________________
            </p>
        </div>
    <div class="container text-center">
            <p class="">
                    <h1> Comments from soccer fans in the US </h1> 
                    <h5> Are Americans WATCHING The 2018 World Cup? by the Youssef Twins </h5>  
            </p>
            <div class="m-auto" style="width: 560px;clear:left ">
                    <iframe width="580" height="315" src="https://www.youtube.com/embed/QUgAM64so4U" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen=""></iframe>
            </div>
                
            <p class="">
                    <h5> Why USA didn't qualify for the World Cup 2018 by ELYYT  </h5>  
            </p>
            <div class="m-auto" style="width: 560px;column-fill:left ">
                    <iframe width="560" height="315" src="https://www.youtube.com/embed/laZ865n3d38" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen=""></iframe>
            </div>

        </div>
        
{% endblock %}

templates/scores.html
{% extends "base.html" %}

{% block content %}

    <table class="table">
        <thead>
          <tr>
            <th scope="col">Date</th>
            <th scope="col">Minute</th>
            <th scope="col">Match</th>
            <th scope="col">Score</th>
          </tr>
        </thead>
        {% if score_list|length == 0 %}
          <tr>
              <td> None </td>
              <td> None </td>
              <td> None </td>
              <td> None </td>
          </tr>
        {% else %}
          {% for match in score_list %}
            <tbody>
              <tr>
                  <td> {{ match.curr_match.date }}</td>
                  <td> {{ match.minute }} </td>
                  <td> {{ match.curr_match.LeftTeam}} vs. {{ match.curr_match.RightTeam }}</td>
                  <td> {{ match.score.leftScore }} - {{ match.score.rightScore}} </td>
              </tr>
            </tbody>
          {% endfor %}
        {% endif %}
      </table>

{% endblock %}

templates/team.html
{% extends "base.html" %}
{% load staticfiles %}
    {% block head %}
        <title> {{ team_query.teamName }} </title>
        <style>
            body
            {
                background-image: url("{% static 'images/'|add:team_query.teamName|add:'Opa.png' %}");
                background-repeat: no-repeat;
                background-position: 650px 100px;
                background-size: 600px 600px;
            }
        </style>
    {% endblock %}

{% block content %}

        <table class="table">
            <thead>
            <tr>
                <th scope="col">Team</th>
                <th scope="col">isEliminated</th>
                <th scope="col">Total Goals </th>
            </tr>
            </thead>
            <tbody>
                <tr>
                    <td> {{ team_query.teamName }}</td>
                    {% if team_query.isEliminated == True %}
                        <td> Yes </td>
                    {% else %}
                        <td> No </td>
                    {% endif %}
                    <td> {{ team_query.totalGoals }} </td>
                </tr>
            </tbody>
        </table>
        <img src = "{% static 'images/'|add:team_query.teamName|add:'.jpg' %}" class= "rounded" style = "max-height: 400px">
    </div>

{% endblock %}

templates/team_search.html
{% extends "base.html" %}

{% block head %}
    <style>
        /* Sticky footer styles
    -------------------------------------------------- */
        html {
            position: relative;
            min-height: 100%;
        }

        .card-footer {
            position: absolute;
            bottom: 0;
            width: 100%;
            /* Set the fixed height of the footer here */

        }

    </style>
{% endblock %}

{% block content %}

    <div class="jumbotron">

    <form method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Submit" />
    </form>

    </div>

{% endblock %}

templates/twitter.html
{% extends "base.html" %}

{% block content %}

    <table class="table">
        <thead>
          <tr>
            <th scope="col">User</th>
            <th scope="col">Tweet</th>
            <th scope="col">link</th>
          </tr>
        </thead>
        {% for item in tweet_list %}
            <tbody>
            <tr>
                <td> {{ item.user }} </td>
                <td> {{ item.text }}</td>
                {% if item.link != None %}
                        <td><a href="{{ item.link }}"> {{ item.link }}</a></td>
                {% endif %}
            </tr>
            </tbody>
        {% endfor %}
      </table>

{% endblock %}